#  ______                     __             ___ ___       __ 
# |   _  \ .-----.-----.---.-|  |_.-----.   |   Y   .-----|  |
# |.  |   \|  _  |     |  _  |   _|  -__|   |.      |  -__|__|
# |.  |    |_____|__|__|___._|____|_____|   |. \_/  |_____|__|
# |:  1    /                                |:  |   |         
# |::.. . /                                 |::.|:. |         
# `------'                                  `--- ---'         
                                                             
custom: ["https://revolut.me/adrianu8cv"]

